sudo: false

os:
  - linux

language: d

d:
  - dmd-2.072.0
  - dmd-2.071.2
  - dmd-2.070.2
  - dmd-2.069.2
  - ldc-1.1.0-beta2
  - ldc-1.0.0

matrix:
  include:
    - os: osx
      d: dmd-2.072.0
    - os: osx
      d: ldc-1.0.0

script:
 - dub test -b unittest-cov --compiler=${DC}
after_success:
 - bash <(curl -s https://codecov.io/bash)
