sudo: false

os:
  - linux

language: d

d:
  - dmd-2.077.0
  - dmd-2.076.1
  - dmd-2.075.1
  - dmd-2.074.1
  - ldc-1.6.0
  - ldc-1.5.0

script:
 - dub test -b unittest-cov --compiler=${DC}
after_success:
 - bash <(curl -s https://codecov.io/bash)
